package io.github.hosseinkarami_dev.near.rpc.models

import kotlin.collections.List
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class IndexerChunkView(
  @SerialName("author")
  public val author: AccountId,
  @SerialName("header")
  public val `header`: ChunkHeaderView,
  /**
   *  * Receipts that were processed instantly in the same chunk they were created.
   */
  @SerialName("instant_receipts")
  public val instantReceipts: List<ReceiptView>? = listOf(),
  /**
   *  * Receipts generated in this chunk from transactions with `signer_id`
   * equal to `receiver_id`.
   */
  @SerialName("local_receipts")
  public val localReceipts: List<ReceiptView>? = listOf(),
  /**
   *  * Represents receipts generated by execution of the previous chunk.
   * Note that those are not the receipts executed by this chunk or even
   * targeting that shard.
   */
  @SerialName("receipts")
  public val receipts: List<ReceiptView>,
  @SerialName("transactions")
  public val transactions: List<IndexerTransactionWithOutcome>,
)
