package io.github.hosseinkarami_dev.near.rpc.serializers

import io.github.hosseinkarami_dev.near.rpc.serializers.BlindUnionSerializer
import io.github.hosseinkarami_dev.near.rpc.serializers.Variant
import io.github.hosseinkarami_dev.near.rpc.serializers.VariantKind
import kotlinx.serialization.KSerializer
import kotlinx.serialization.builtins.ListSerializer
import kotlinx.serialization.builtins.MapSerializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import kotlinx.serialization.serializer
import io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError

object ActionsValidationErrorSerializer : KSerializer<ActionsValidationError> {
    private val union: BlindUnionSerializer<ActionsValidationError> = BlindUnionSerializer(
        serialName = "io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError",
        variants = listOf(
            Variant(serialName = "DeleteActionMustBeFinal", kind = VariantKind.OBJECT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.DeleteActionMustBeFinal }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.DeleteActionMustBeFinal>() as KSerializer<Any?>, objectInstance = io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.DeleteActionMustBeFinal),
            Variant(serialName = "TotalPrepaidGasExceeded", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.TotalPrepaidGasExceeded }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.TotalPrepaidGasExceeded>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.TotalPrepaidGasExceeded.TotalPrepaidGasExceededPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.TotalPrepaidGasExceeded).totalPrepaidGasExceeded }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.TotalPrepaidGasExceeded(it as io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.TotalPrepaidGasExceeded.TotalPrepaidGasExceededPayload) }, fields = listOf("TotalPrepaidGasExceeded")),
            Variant(serialName = "TotalNumberOfActionsExceeded", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.TotalNumberOfActionsExceeded }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.TotalNumberOfActionsExceeded>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.TotalNumberOfActionsExceeded.TotalNumberOfActionsExceededPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.TotalNumberOfActionsExceeded).totalNumberOfActionsExceeded }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.TotalNumberOfActionsExceeded(it as io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.TotalNumberOfActionsExceeded.TotalNumberOfActionsExceededPayload) }, fields = listOf("TotalNumberOfActionsExceeded")),
            Variant(serialName = "AddKeyMethodNamesNumberOfBytesExceeded", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.AddKeyMethodNamesNumberOfBytesExceeded }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.AddKeyMethodNamesNumberOfBytesExceeded>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.AddKeyMethodNamesNumberOfBytesExceeded.AddKeyMethodNamesNumberOfBytesExceededPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.AddKeyMethodNamesNumberOfBytesExceeded).addKeyMethodNamesNumberOfBytesExceeded }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.AddKeyMethodNamesNumberOfBytesExceeded(it as io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.AddKeyMethodNamesNumberOfBytesExceeded.AddKeyMethodNamesNumberOfBytesExceededPayload) }, fields = listOf("AddKeyMethodNamesNumberOfBytesExceeded")),
            Variant(serialName = "AddKeyMethodNameLengthExceeded", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.AddKeyMethodNameLengthExceeded }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.AddKeyMethodNameLengthExceeded>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.AddKeyMethodNameLengthExceeded.AddKeyMethodNameLengthExceededPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.AddKeyMethodNameLengthExceeded).addKeyMethodNameLengthExceeded }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.AddKeyMethodNameLengthExceeded(it as io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.AddKeyMethodNameLengthExceeded.AddKeyMethodNameLengthExceededPayload) }, fields = listOf("AddKeyMethodNameLengthExceeded")),
            Variant(serialName = "IntegerOverflow", kind = VariantKind.OBJECT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.IntegerOverflow }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.IntegerOverflow>() as KSerializer<Any?>, objectInstance = io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.IntegerOverflow),
            Variant(serialName = "InvalidAccountId", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.InvalidAccountId }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.InvalidAccountId>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.InvalidAccountId.InvalidAccountIdPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.InvalidAccountId).invalidAccountId }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.InvalidAccountId(it as io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.InvalidAccountId.InvalidAccountIdPayload) }, fields = listOf("InvalidAccountId")),
            Variant(serialName = "ContractSizeExceeded", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.ContractSizeExceeded }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.ContractSizeExceeded>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.ContractSizeExceeded.ContractSizeExceededPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.ContractSizeExceeded).contractSizeExceeded }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.ContractSizeExceeded(it as io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.ContractSizeExceeded.ContractSizeExceededPayload) }, fields = listOf("ContractSizeExceeded")),
            Variant(serialName = "FunctionCallMethodNameLengthExceeded", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.FunctionCallMethodNameLengthExceeded }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.FunctionCallMethodNameLengthExceeded>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.FunctionCallMethodNameLengthExceeded.FunctionCallMethodNameLengthExceededPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.FunctionCallMethodNameLengthExceeded).functionCallMethodNameLengthExceeded }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.FunctionCallMethodNameLengthExceeded(it as io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.FunctionCallMethodNameLengthExceeded.FunctionCallMethodNameLengthExceededPayload) }, fields = listOf("FunctionCallMethodNameLengthExceeded")),
            Variant(serialName = "FunctionCallArgumentsLengthExceeded", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.FunctionCallArgumentsLengthExceeded }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.FunctionCallArgumentsLengthExceeded>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.FunctionCallArgumentsLengthExceeded.FunctionCallArgumentsLengthExceededPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.FunctionCallArgumentsLengthExceeded).functionCallArgumentsLengthExceeded }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.FunctionCallArgumentsLengthExceeded(it as io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.FunctionCallArgumentsLengthExceeded.FunctionCallArgumentsLengthExceededPayload) }, fields = listOf("FunctionCallArgumentsLengthExceeded")),
            Variant(serialName = "UnsuitableStakingKey", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.UnsuitableStakingKey }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.UnsuitableStakingKey>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.UnsuitableStakingKey.UnsuitableStakingKeyPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.UnsuitableStakingKey).unsuitableStakingKey }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.UnsuitableStakingKey(it as io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.UnsuitableStakingKey.UnsuitableStakingKeyPayload) }, fields = listOf("UnsuitableStakingKey")),
            Variant(serialName = "FunctionCallZeroAttachedGas", kind = VariantKind.OBJECT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.FunctionCallZeroAttachedGas }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.FunctionCallZeroAttachedGas>() as KSerializer<Any?>, objectInstance = io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.FunctionCallZeroAttachedGas),
            Variant(serialName = "DelegateActionMustBeOnlyOne", kind = VariantKind.OBJECT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.DelegateActionMustBeOnlyOne }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.DelegateActionMustBeOnlyOne>() as KSerializer<Any?>, objectInstance = io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.DelegateActionMustBeOnlyOne),
            Variant(serialName = "UnsupportedProtocolFeature", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.UnsupportedProtocolFeature }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.UnsupportedProtocolFeature>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.UnsupportedProtocolFeature.UnsupportedProtocolFeaturePayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.UnsupportedProtocolFeature).unsupportedProtocolFeature }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.UnsupportedProtocolFeature(it as io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.UnsupportedProtocolFeature.UnsupportedProtocolFeaturePayload) }, fields = listOf("UnsupportedProtocolFeature")),
            Variant(serialName = "InvalidDeterministicStateInitReceiver", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.InvalidDeterministicStateInitReceiver }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.InvalidDeterministicStateInitReceiver>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.InvalidDeterministicStateInitReceiver.InvalidDeterministicStateInitReceiverPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.InvalidDeterministicStateInitReceiver).invalidDeterministicStateInitReceiver }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.InvalidDeterministicStateInitReceiver(it as io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.InvalidDeterministicStateInitReceiver.InvalidDeterministicStateInitReceiverPayload) }, fields = listOf("InvalidDeterministicStateInitReceiver")),
            Variant(serialName = "DeterministicStateInitKeyLengthExceeded", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.DeterministicStateInitKeyLengthExceeded }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.DeterministicStateInitKeyLengthExceeded>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.DeterministicStateInitKeyLengthExceeded.DeterministicStateInitKeyLengthExceededPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.DeterministicStateInitKeyLengthExceeded).deterministicStateInitKeyLengthExceeded }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.DeterministicStateInitKeyLengthExceeded(it as io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.DeterministicStateInitKeyLengthExceeded.DeterministicStateInitKeyLengthExceededPayload) }, fields = listOf("DeterministicStateInitKeyLengthExceeded")),
            Variant(serialName = "DeterministicStateInitValueLengthExceeded", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.DeterministicStateInitValueLengthExceeded }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.DeterministicStateInitValueLengthExceeded>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.DeterministicStateInitValueLengthExceeded.DeterministicStateInitValueLengthExceededPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.DeterministicStateInitValueLengthExceeded).deterministicStateInitValueLengthExceeded }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.DeterministicStateInitValueLengthExceeded(it as io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.DeterministicStateInitValueLengthExceeded.DeterministicStateInitValueLengthExceededPayload) }, fields = listOf("DeterministicStateInitValueLengthExceeded")),
            Variant(serialName = "GasKeyInvalidNumNonces", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.GasKeyInvalidNumNonces }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.GasKeyInvalidNumNonces>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.GasKeyInvalidNumNonces.GasKeyInvalidNumNoncesPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.GasKeyInvalidNumNonces).gasKeyInvalidNumNonces }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.GasKeyInvalidNumNonces(it as io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.GasKeyInvalidNumNonces.GasKeyInvalidNumNoncesPayload) }, fields = listOf("GasKeyInvalidNumNonces")),
            Variant(serialName = "AddGasKeyWithNonZeroBalance", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.AddGasKeyWithNonZeroBalance }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.AddGasKeyWithNonZeroBalance>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.AddGasKeyWithNonZeroBalance.AddGasKeyWithNonZeroBalancePayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.AddGasKeyWithNonZeroBalance).addGasKeyWithNonZeroBalance }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.AddGasKeyWithNonZeroBalance(it as io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.AddGasKeyWithNonZeroBalance.AddGasKeyWithNonZeroBalancePayload) }, fields = listOf("AddGasKeyWithNonZeroBalance")),
            Variant(serialName = "GasKeyFunctionCallAllowanceNotAllowed", kind = VariantKind.OBJECT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.GasKeyFunctionCallAllowanceNotAllowed }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.GasKeyFunctionCallAllowanceNotAllowed>() as KSerializer<Any?>, objectInstance = io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.GasKeyFunctionCallAllowanceNotAllowed),
            Variant(serialName = "TotalNumberOfDeployActionsExceeded", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.TotalNumberOfDeployActionsExceeded }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.TotalNumberOfDeployActionsExceeded>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.TotalNumberOfDeployActionsExceeded.TotalNumberOfDeployActionsExceededPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.TotalNumberOfDeployActionsExceeded).totalNumberOfDeployActionsExceeded }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.TotalNumberOfDeployActionsExceeded(it as io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.TotalNumberOfDeployActionsExceeded.TotalNumberOfDeployActionsExceededPayload) }, fields = listOf("TotalNumberOfDeployActionsExceeded")),
            Variant(serialName = "FunctionCallEmptyMethodName", kind = VariantKind.OBJECT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.FunctionCallEmptyMethodName }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.FunctionCallEmptyMethodName>() as KSerializer<Any?>, objectInstance = io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.FunctionCallEmptyMethodName),
            Variant(serialName = "InvalidUniversalStateInitReceiver", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.InvalidUniversalStateInitReceiver }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.InvalidUniversalStateInitReceiver>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.InvalidUniversalStateInitReceiver.InvalidUniversalStateInitReceiverPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.InvalidUniversalStateInitReceiver).invalidUniversalStateInitReceiver }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.InvalidUniversalStateInitReceiver(it as io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.InvalidUniversalStateInitReceiver.InvalidUniversalStateInitReceiverPayload) }, fields = listOf("InvalidUniversalStateInitReceiver")),
            Variant(serialName = "UniversalStateInitKeyLengthExceeded", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.UniversalStateInitKeyLengthExceeded }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.UniversalStateInitKeyLengthExceeded>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.UniversalStateInitKeyLengthExceeded.UniversalStateInitKeyLengthExceededPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.UniversalStateInitKeyLengthExceeded).universalStateInitKeyLengthExceeded }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.UniversalStateInitKeyLengthExceeded(it as io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.UniversalStateInitKeyLengthExceeded.UniversalStateInitKeyLengthExceededPayload) }, fields = listOf("UniversalStateInitKeyLengthExceeded")),
            Variant(serialName = "UniversalStateInitValueLengthExceeded", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.UniversalStateInitValueLengthExceeded }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.UniversalStateInitValueLengthExceeded>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.UniversalStateInitValueLengthExceeded.UniversalStateInitValueLengthExceededPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.UniversalStateInitValueLengthExceeded).universalStateInitValueLengthExceeded }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.UniversalStateInitValueLengthExceeded(it as io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.UniversalStateInitValueLengthExceeded.UniversalStateInitValueLengthExceededPayload) }, fields = listOf("UniversalStateInitValueLengthExceeded")),
            Variant(serialName = "MalformedUniversalStateInit", kind = VariantKind.OBJECT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.MalformedUniversalStateInit }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.MalformedUniversalStateInit>() as KSerializer<Any?>, objectInstance = io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.MalformedUniversalStateInit),
            Variant(serialName = "RemovedProtocolFeature", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.RemovedProtocolFeature }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.RemovedProtocolFeature>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.RemovedProtocolFeature.RemovedProtocolFeaturePayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.RemovedProtocolFeature).removedProtocolFeature }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.RemovedProtocolFeature(it as io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.RemovedProtocolFeature.RemovedProtocolFeaturePayload) }, fields = listOf("RemovedProtocolFeature")),
            Variant(serialName = "WithdrawFromGasKeyNotAllowedInDelegate", kind = VariantKind.OBJECT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.WithdrawFromGasKeyNotAllowedInDelegate }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.WithdrawFromGasKeyNotAllowedInDelegate>() as KSerializer<Any?>, objectInstance = io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError.WithdrawFromGasKeyNotAllowedInDelegate)
        )
    )

    override val descriptor = union.descriptor
    override fun serialize(encoder: Encoder, value: ActionsValidationError) = union.serialize(encoder, value)
    override fun deserialize(decoder: Decoder): ActionsValidationError = union.deserialize(decoder)
}
