package io.github.hosseinkarami_dev.near.rpc.serializers

import io.github.hosseinkarami_dev.near.rpc.serializers.BlindUnionSerializer
import io.github.hosseinkarami_dev.near.rpc.serializers.Variant
import io.github.hosseinkarami_dev.near.rpc.serializers.VariantKind
import kotlinx.serialization.KSerializer
import kotlinx.serialization.builtins.ListSerializer
import kotlinx.serialization.builtins.MapSerializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import kotlinx.serialization.serializer
import io.github.hosseinkarami_dev.near.rpc.models.NonDelegateAction

object NonDelegateActionSerializer : KSerializer<NonDelegateAction> {
    private val union: BlindUnionSerializer<NonDelegateAction> = BlindUnionSerializer(
        serialName = "io.github.hosseinkarami_dev.near.rpc.models.NonDelegateAction",
        variants = listOf(
            Variant(serialName = "CreateAccount", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.NonDelegateAction.CreateAccount }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.NonDelegateAction.CreateAccount>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.CreateAccountAction>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.NonDelegateAction.CreateAccount).createAccount }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.NonDelegateAction.CreateAccount(it as io.github.hosseinkarami_dev.near.rpc.models.CreateAccountAction) }, fields = listOf("CreateAccount")),
            Variant(serialName = "DeployContract", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.NonDelegateAction.DeployContract }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.NonDelegateAction.DeployContract>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.DeployContractAction>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.NonDelegateAction.DeployContract).deployContract }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.NonDelegateAction.DeployContract(it as io.github.hosseinkarami_dev.near.rpc.models.DeployContractAction) }, fields = listOf("DeployContract")),
            Variant(serialName = "FunctionCall", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.NonDelegateAction.FunctionCall }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.NonDelegateAction.FunctionCall>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.FunctionCallAction>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.NonDelegateAction.FunctionCall).functionCall }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.NonDelegateAction.FunctionCall(it as io.github.hosseinkarami_dev.near.rpc.models.FunctionCallAction) }, fields = listOf("FunctionCall")),
            Variant(serialName = "Transfer", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.NonDelegateAction.Transfer }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.NonDelegateAction.Transfer>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.TransferAction>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.NonDelegateAction.Transfer).transfer }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.NonDelegateAction.Transfer(it as io.github.hosseinkarami_dev.near.rpc.models.TransferAction) }, fields = listOf("Transfer")),
            Variant(serialName = "Stake", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.NonDelegateAction.Stake }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.NonDelegateAction.Stake>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.StakeAction>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.NonDelegateAction.Stake).stake }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.NonDelegateAction.Stake(it as io.github.hosseinkarami_dev.near.rpc.models.StakeAction) }, fields = listOf("Stake")),
            Variant(serialName = "AddKey", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.NonDelegateAction.AddKey }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.NonDelegateAction.AddKey>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.AddKeyAction>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.NonDelegateAction.AddKey).addKey }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.NonDelegateAction.AddKey(it as io.github.hosseinkarami_dev.near.rpc.models.AddKeyAction) }, fields = listOf("AddKey")),
            Variant(serialName = "DeleteKey", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.NonDelegateAction.DeleteKey }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.NonDelegateAction.DeleteKey>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.DeleteKeyAction>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.NonDelegateAction.DeleteKey).deleteKey }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.NonDelegateAction.DeleteKey(it as io.github.hosseinkarami_dev.near.rpc.models.DeleteKeyAction) }, fields = listOf("DeleteKey")),
            Variant(serialName = "DeleteAccount", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.NonDelegateAction.DeleteAccount }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.NonDelegateAction.DeleteAccount>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.DeleteAccountAction>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.NonDelegateAction.DeleteAccount).deleteAccount }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.NonDelegateAction.DeleteAccount(it as io.github.hosseinkarami_dev.near.rpc.models.DeleteAccountAction) }, fields = listOf("DeleteAccount")),
            Variant(serialName = "DeployGlobalContract", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.NonDelegateAction.DeployGlobalContract }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.NonDelegateAction.DeployGlobalContract>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.DeployGlobalContractAction>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.NonDelegateAction.DeployGlobalContract).deployGlobalContract }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.NonDelegateAction.DeployGlobalContract(it as io.github.hosseinkarami_dev.near.rpc.models.DeployGlobalContractAction) }, fields = listOf("DeployGlobalContract")),
            Variant(serialName = "UseGlobalContract", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.NonDelegateAction.UseGlobalContract }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.NonDelegateAction.UseGlobalContract>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.UseGlobalContractAction>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.NonDelegateAction.UseGlobalContract).useGlobalContract }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.NonDelegateAction.UseGlobalContract(it as io.github.hosseinkarami_dev.near.rpc.models.UseGlobalContractAction) }, fields = listOf("UseGlobalContract")),
            Variant(serialName = "DeterministicStateInit", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.NonDelegateAction.DeterministicStateInit }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.NonDelegateAction.DeterministicStateInit>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.DeterministicStateInitAction>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.NonDelegateAction.DeterministicStateInit).deterministicStateInit }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.NonDelegateAction.DeterministicStateInit(it as io.github.hosseinkarami_dev.near.rpc.models.DeterministicStateInitAction) }, fields = listOf("DeterministicStateInit")),
            Variant(serialName = "TransferToGasKey", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.NonDelegateAction.TransferToGasKey }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.NonDelegateAction.TransferToGasKey>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.TransferToGasKeyAction>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.NonDelegateAction.TransferToGasKey).transferToGasKey }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.NonDelegateAction.TransferToGasKey(it as io.github.hosseinkarami_dev.near.rpc.models.TransferToGasKeyAction) }, fields = listOf("TransferToGasKey")),
            Variant(serialName = "WithdrawFromGasKey", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.NonDelegateAction.WithdrawFromGasKey }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.NonDelegateAction.WithdrawFromGasKey>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.WithdrawFromGasKeyAction>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.NonDelegateAction.WithdrawFromGasKey).withdrawFromGasKey }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.NonDelegateAction.WithdrawFromGasKey(it as io.github.hosseinkarami_dev.near.rpc.models.WithdrawFromGasKeyAction) }, fields = listOf("WithdrawFromGasKey")),
            Variant(serialName = "UniversalStateInit", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.NonDelegateAction.UniversalStateInit }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.NonDelegateAction.UniversalStateInit>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.UniversalStateInitAction>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.NonDelegateAction.UniversalStateInit).universalStateInit }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.NonDelegateAction.UniversalStateInit(it as io.github.hosseinkarami_dev.near.rpc.models.UniversalStateInitAction) }, fields = listOf("UniversalStateInit"))
        )
    )

    override val descriptor = union.descriptor
    override fun serialize(encoder: Encoder, value: NonDelegateAction) = union.serialize(encoder, value)
    override fun deserialize(decoder: Decoder): NonDelegateAction = union.deserialize(decoder)
}
