package io.github.hosseinkarami_dev.near.rpc.serializers

import io.github.hosseinkarami_dev.near.rpc.serializers.BlindUnionSerializer
import io.github.hosseinkarami_dev.near.rpc.serializers.Variant
import io.github.hosseinkarami_dev.near.rpc.serializers.VariantKind
import kotlinx.serialization.KSerializer
import kotlinx.serialization.builtins.ListSerializer
import kotlinx.serialization.builtins.MapSerializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import kotlinx.serialization.serializer
import io.github.hosseinkarami_dev.near.rpc.models.PrepareError

object PrepareErrorSerializer : KSerializer<PrepareError> {
    private val union: BlindUnionSerializer<PrepareError> = BlindUnionSerializer(
        serialName = "io.github.hosseinkarami_dev.near.rpc.models.PrepareError",
        variants = listOf(
            Variant(serialName = "Serialization", kind = VariantKind.OBJECT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.PrepareError.Serialization }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.PrepareError.Serialization>() as KSerializer<Any?>, objectInstance = io.github.hosseinkarami_dev.near.rpc.models.PrepareError.Serialization),
            Variant(serialName = "Deserialization", kind = VariantKind.OBJECT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.PrepareError.Deserialization }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.PrepareError.Deserialization>() as KSerializer<Any?>, objectInstance = io.github.hosseinkarami_dev.near.rpc.models.PrepareError.Deserialization),
            Variant(serialName = "InternalMemoryDeclared", kind = VariantKind.OBJECT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.PrepareError.InternalMemoryDeclared }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.PrepareError.InternalMemoryDeclared>() as KSerializer<Any?>, objectInstance = io.github.hosseinkarami_dev.near.rpc.models.PrepareError.InternalMemoryDeclared),
            Variant(serialName = "GasInstrumentation", kind = VariantKind.OBJECT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.PrepareError.GasInstrumentation }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.PrepareError.GasInstrumentation>() as KSerializer<Any?>, objectInstance = io.github.hosseinkarami_dev.near.rpc.models.PrepareError.GasInstrumentation),
            Variant(serialName = "StackHeightInstrumentation", kind = VariantKind.OBJECT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.PrepareError.StackHeightInstrumentation }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.PrepareError.StackHeightInstrumentation>() as KSerializer<Any?>, objectInstance = io.github.hosseinkarami_dev.near.rpc.models.PrepareError.StackHeightInstrumentation),
            Variant(serialName = "Instantiate", kind = VariantKind.OBJECT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.PrepareError.Instantiate }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.PrepareError.Instantiate>() as KSerializer<Any?>, objectInstance = io.github.hosseinkarami_dev.near.rpc.models.PrepareError.Instantiate),
            Variant(serialName = "Memory", kind = VariantKind.OBJECT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.PrepareError.Memory }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.PrepareError.Memory>() as KSerializer<Any?>, objectInstance = io.github.hosseinkarami_dev.near.rpc.models.PrepareError.Memory),
            Variant(serialName = "TooManyFunctions", kind = VariantKind.OBJECT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.PrepareError.TooManyFunctions }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.PrepareError.TooManyFunctions>() as KSerializer<Any?>, objectInstance = io.github.hosseinkarami_dev.near.rpc.models.PrepareError.TooManyFunctions),
            Variant(serialName = "TooManyLocals", kind = VariantKind.OBJECT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.PrepareError.TooManyLocals }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.PrepareError.TooManyLocals>() as KSerializer<Any?>, objectInstance = io.github.hosseinkarami_dev.near.rpc.models.PrepareError.TooManyLocals),
            Variant(serialName = "TooManyTables", kind = VariantKind.OBJECT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.PrepareError.TooManyTables }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.PrepareError.TooManyTables>() as KSerializer<Any?>, objectInstance = io.github.hosseinkarami_dev.near.rpc.models.PrepareError.TooManyTables),
            Variant(serialName = "TooManyTableElements", kind = VariantKind.OBJECT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.PrepareError.TooManyTableElements }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.PrepareError.TooManyTableElements>() as KSerializer<Any?>, objectInstance = io.github.hosseinkarami_dev.near.rpc.models.PrepareError.TooManyTableElements),
            Variant(serialName = "FunctionBodyTooLarge", kind = VariantKind.OBJECT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.PrepareError.FunctionBodyTooLarge }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.PrepareError.FunctionBodyTooLarge>() as KSerializer<Any?>, objectInstance = io.github.hosseinkarami_dev.near.rpc.models.PrepareError.FunctionBodyTooLarge),
            Variant(serialName = "InstrumentedCodeTooLarge", kind = VariantKind.OBJECT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.PrepareError.InstrumentedCodeTooLarge }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.PrepareError.InstrumentedCodeTooLarge>() as KSerializer<Any?>, objectInstance = io.github.hosseinkarami_dev.near.rpc.models.PrepareError.InstrumentedCodeTooLarge),
            Variant(serialName = "TooManyBlocksPerFunction", kind = VariantKind.OBJECT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.PrepareError.TooManyBlocksPerFunction }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.PrepareError.TooManyBlocksPerFunction>() as KSerializer<Any?>, objectInstance = io.github.hosseinkarami_dev.near.rpc.models.PrepareError.TooManyBlocksPerFunction),
            Variant(serialName = "TooManyBlocksPerContract", kind = VariantKind.OBJECT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.PrepareError.TooManyBlocksPerContract }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.PrepareError.TooManyBlocksPerContract>() as KSerializer<Any?>, objectInstance = io.github.hosseinkarami_dev.near.rpc.models.PrepareError.TooManyBlocksPerContract),
            Variant(serialName = "TooManyTypes", kind = VariantKind.OBJECT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.PrepareError.TooManyTypes }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.PrepareError.TooManyTypes>() as KSerializer<Any?>, objectInstance = io.github.hosseinkarami_dev.near.rpc.models.PrepareError.TooManyTypes),
            Variant(serialName = "TooManyParamsPerFunction", kind = VariantKind.OBJECT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.PrepareError.TooManyParamsPerFunction }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.PrepareError.TooManyParamsPerFunction>() as KSerializer<Any?>, objectInstance = io.github.hosseinkarami_dev.near.rpc.models.PrepareError.TooManyParamsPerFunction),
            Variant(serialName = "TooManyParamsPerContract", kind = VariantKind.OBJECT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.PrepareError.TooManyParamsPerContract }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.PrepareError.TooManyParamsPerContract>() as KSerializer<Any?>, objectInstance = io.github.hosseinkarami_dev.near.rpc.models.PrepareError.TooManyParamsPerContract),
            Variant(serialName = "OperandStackTooLarge", kind = VariantKind.OBJECT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.PrepareError.OperandStackTooLarge }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.PrepareError.OperandStackTooLarge>() as KSerializer<Any?>, objectInstance = io.github.hosseinkarami_dev.near.rpc.models.PrepareError.OperandStackTooLarge),
            Variant(serialName = "TooManyGlobals", kind = VariantKind.OBJECT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.PrepareError.TooManyGlobals }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.PrepareError.TooManyGlobals>() as KSerializer<Any?>, objectInstance = io.github.hosseinkarami_dev.near.rpc.models.PrepareError.TooManyGlobals)
        )
    )

    override val descriptor = union.descriptor
    override fun serialize(encoder: Encoder, value: PrepareError) = union.serialize(encoder, value)
    override fun deserialize(decoder: Decoder): PrepareError = union.deserialize(decoder)
}
