package io.github.hosseinkarami_dev.near.rpc.serializers

import io.github.hosseinkarami_dev.near.rpc.serializers.BlindUnionSerializer
import io.github.hosseinkarami_dev.near.rpc.serializers.Variant
import io.github.hosseinkarami_dev.near.rpc.serializers.VariantKind
import kotlinx.serialization.KSerializer
import kotlinx.serialization.builtins.ListSerializer
import kotlinx.serialization.builtins.MapSerializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import kotlinx.serialization.serializer
import io.github.hosseinkarami_dev.near.rpc.models.RpcQueryRequest

object RpcQueryRequestSerializer : KSerializer<RpcQueryRequest> {
    private val union: BlindUnionSerializer<RpcQueryRequest> = BlindUnionSerializer(
        serialName = "io.github.hosseinkarami_dev.near.rpc.models.RpcQueryRequest",
        variants = listOf(
            Variant(serialName = "view_account_by_block_id", kind = VariantKind.DEFAULT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.RpcQueryRequest.ViewAccountByBlockId }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.RpcQueryRequest.ViewAccountByBlockId>() as KSerializer<Any?>, fields = listOf("block_id", "account_id", "request_type")),
            Variant(serialName = "view_code_by_block_id", kind = VariantKind.DEFAULT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.RpcQueryRequest.ViewCodeByBlockId }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.RpcQueryRequest.ViewCodeByBlockId>() as KSerializer<Any?>, fields = listOf("block_id", "account_id", "request_type")),
            Variant(serialName = "view_state_by_block_id", kind = VariantKind.DEFAULT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.RpcQueryRequest.ViewStateByBlockId }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.RpcQueryRequest.ViewStateByBlockId>() as KSerializer<Any?>, fields = listOf("block_id", "account_id", "after_key_base64", "include_proof", "limit", "prefix_base64", "request_type")),
            Variant(serialName = "view_access_key_by_block_id", kind = VariantKind.DEFAULT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.RpcQueryRequest.ViewAccessKeyByBlockId }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.RpcQueryRequest.ViewAccessKeyByBlockId>() as KSerializer<Any?>, fields = listOf("block_id", "account_id", "public_key", "request_type")),
            Variant(serialName = "view_access_key_list_by_block_id", kind = VariantKind.DEFAULT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.RpcQueryRequest.ViewAccessKeyListByBlockId }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.RpcQueryRequest.ViewAccessKeyListByBlockId>() as KSerializer<Any?>, fields = listOf("block_id", "account_id", "after_key", "limit", "request_type")),
            Variant(serialName = "view_gas_key_nonces_by_block_id", kind = VariantKind.DEFAULT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.RpcQueryRequest.ViewGasKeyNoncesByBlockId }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.RpcQueryRequest.ViewGasKeyNoncesByBlockId>() as KSerializer<Any?>, fields = listOf("block_id", "account_id", "public_key", "request_type")),
            Variant(serialName = "call_function_by_block_id", kind = VariantKind.DEFAULT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.RpcQueryRequest.CallFunctionByBlockId }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.RpcQueryRequest.CallFunctionByBlockId>() as KSerializer<Any?>, fields = listOf("block_id", "account_id", "args_base64", "method_name", "request_type")),
            Variant(serialName = "view_global_contract_code_by_block_id", kind = VariantKind.DEFAULT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.RpcQueryRequest.ViewGlobalContractCodeByBlockId }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.RpcQueryRequest.ViewGlobalContractCodeByBlockId>() as KSerializer<Any?>, fields = listOf("block_id", "code_hash", "request_type")),
            Variant(serialName = "view_global_contract_code_by_account_id_by_block_id", kind = VariantKind.DEFAULT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.RpcQueryRequest.ViewGlobalContractCodeByAccountIdByBlockId }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.RpcQueryRequest.ViewGlobalContractCodeByAccountIdByBlockId>() as KSerializer<Any?>, fields = listOf("block_id", "account_id", "request_type")),
            Variant(serialName = "view_account_by_finality", kind = VariantKind.DEFAULT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.RpcQueryRequest.ViewAccountByFinality }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.RpcQueryRequest.ViewAccountByFinality>() as KSerializer<Any?>, fields = listOf("finality", "account_id", "request_type")),
            Variant(serialName = "view_code_by_finality", kind = VariantKind.DEFAULT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.RpcQueryRequest.ViewCodeByFinality }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.RpcQueryRequest.ViewCodeByFinality>() as KSerializer<Any?>, fields = listOf("finality", "account_id", "request_type")),
            Variant(serialName = "view_state_by_finality", kind = VariantKind.DEFAULT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.RpcQueryRequest.ViewStateByFinality }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.RpcQueryRequest.ViewStateByFinality>() as KSerializer<Any?>, fields = listOf("finality", "account_id", "after_key_base64", "include_proof", "limit", "prefix_base64", "request_type")),
            Variant(serialName = "view_access_key_by_finality", kind = VariantKind.DEFAULT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.RpcQueryRequest.ViewAccessKeyByFinality }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.RpcQueryRequest.ViewAccessKeyByFinality>() as KSerializer<Any?>, fields = listOf("finality", "account_id", "public_key", "request_type")),
            Variant(serialName = "view_access_key_list_by_finality", kind = VariantKind.DEFAULT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.RpcQueryRequest.ViewAccessKeyListByFinality }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.RpcQueryRequest.ViewAccessKeyListByFinality>() as KSerializer<Any?>, fields = listOf("finality", "account_id", "after_key", "limit", "request_type")),
            Variant(serialName = "view_gas_key_nonces_by_finality", kind = VariantKind.DEFAULT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.RpcQueryRequest.ViewGasKeyNoncesByFinality }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.RpcQueryRequest.ViewGasKeyNoncesByFinality>() as KSerializer<Any?>, fields = listOf("finality", "account_id", "public_key", "request_type")),
            Variant(serialName = "call_function_by_finality", kind = VariantKind.DEFAULT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.RpcQueryRequest.CallFunctionByFinality }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.RpcQueryRequest.CallFunctionByFinality>() as KSerializer<Any?>, fields = listOf("finality", "account_id", "args_base64", "method_name", "request_type")),
            Variant(serialName = "view_global_contract_code_by_finality", kind = VariantKind.DEFAULT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.RpcQueryRequest.ViewGlobalContractCodeByFinality }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.RpcQueryRequest.ViewGlobalContractCodeByFinality>() as KSerializer<Any?>, fields = listOf("finality", "code_hash", "request_type")),
            Variant(serialName = "view_global_contract_code_by_account_id_by_finality", kind = VariantKind.DEFAULT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.RpcQueryRequest.ViewGlobalContractCodeByAccountIdByFinality }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.RpcQueryRequest.ViewGlobalContractCodeByAccountIdByFinality>() as KSerializer<Any?>, fields = listOf("finality", "account_id", "request_type")),
            Variant(serialName = "view_account_by_sync_checkpoint", kind = VariantKind.DEFAULT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.RpcQueryRequest.ViewAccountBySyncCheckpoint }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.RpcQueryRequest.ViewAccountBySyncCheckpoint>() as KSerializer<Any?>, fields = listOf("sync_checkpoint", "account_id", "request_type")),
            Variant(serialName = "view_code_by_sync_checkpoint", kind = VariantKind.DEFAULT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.RpcQueryRequest.ViewCodeBySyncCheckpoint }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.RpcQueryRequest.ViewCodeBySyncCheckpoint>() as KSerializer<Any?>, fields = listOf("sync_checkpoint", "account_id", "request_type")),
            Variant(serialName = "view_state_by_sync_checkpoint", kind = VariantKind.DEFAULT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.RpcQueryRequest.ViewStateBySyncCheckpoint }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.RpcQueryRequest.ViewStateBySyncCheckpoint>() as KSerializer<Any?>, fields = listOf("sync_checkpoint", "account_id", "after_key_base64", "include_proof", "limit", "prefix_base64", "request_type")),
            Variant(serialName = "view_access_key_by_sync_checkpoint", kind = VariantKind.DEFAULT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.RpcQueryRequest.ViewAccessKeyBySyncCheckpoint }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.RpcQueryRequest.ViewAccessKeyBySyncCheckpoint>() as KSerializer<Any?>, fields = listOf("sync_checkpoint", "account_id", "public_key", "request_type")),
            Variant(serialName = "view_access_key_list_by_sync_checkpoint", kind = VariantKind.DEFAULT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.RpcQueryRequest.ViewAccessKeyListBySyncCheckpoint }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.RpcQueryRequest.ViewAccessKeyListBySyncCheckpoint>() as KSerializer<Any?>, fields = listOf("sync_checkpoint", "account_id", "after_key", "limit", "request_type")),
            Variant(serialName = "view_gas_key_nonces_by_sync_checkpoint", kind = VariantKind.DEFAULT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.RpcQueryRequest.ViewGasKeyNoncesBySyncCheckpoint }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.RpcQueryRequest.ViewGasKeyNoncesBySyncCheckpoint>() as KSerializer<Any?>, fields = listOf("sync_checkpoint", "account_id", "public_key", "request_type")),
            Variant(serialName = "call_function_by_sync_checkpoint", kind = VariantKind.DEFAULT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.RpcQueryRequest.CallFunctionBySyncCheckpoint }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.RpcQueryRequest.CallFunctionBySyncCheckpoint>() as KSerializer<Any?>, fields = listOf("sync_checkpoint", "account_id", "args_base64", "method_name", "request_type")),
            Variant(serialName = "view_global_contract_code_by_sync_checkpoint", kind = VariantKind.DEFAULT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.RpcQueryRequest.ViewGlobalContractCodeBySyncCheckpoint }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.RpcQueryRequest.ViewGlobalContractCodeBySyncCheckpoint>() as KSerializer<Any?>, fields = listOf("sync_checkpoint", "code_hash", "request_type")),
            Variant(serialName = "view_global_contract_code_by_account_id_by_sync_checkpoint", kind = VariantKind.DEFAULT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.RpcQueryRequest.ViewGlobalContractCodeByAccountIdBySyncCheckpoint }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.RpcQueryRequest.ViewGlobalContractCodeByAccountIdBySyncCheckpoint>() as KSerializer<Any?>, fields = listOf("sync_checkpoint", "account_id", "request_type"))
        )
    )

    override val descriptor = union.descriptor
    override fun serialize(encoder: Encoder, value: RpcQueryRequest) = union.serialize(encoder, value)
    override fun deserialize(decoder: Decoder): RpcQueryRequest = union.deserialize(decoder)
}
