package io.github.hosseinkarami_dev.near.rpc.serializers

import io.github.hosseinkarami_dev.near.rpc.serializers.BlindUnionSerializer
import io.github.hosseinkarami_dev.near.rpc.serializers.Variant
import io.github.hosseinkarami_dev.near.rpc.serializers.VariantKind
import kotlinx.serialization.KSerializer
import kotlinx.serialization.builtins.ListSerializer
import kotlinx.serialization.builtins.MapSerializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import kotlinx.serialization.serializer
import io.github.hosseinkarami_dev.near.rpc.models.RpcStateChangesInBlockByTypeRequest

object RpcStateChangesInBlockByTypeRequestSerializer : KSerializer<RpcStateChangesInBlockByTypeRequest> {
    private val union: BlindUnionSerializer<RpcStateChangesInBlockByTypeRequest> = BlindUnionSerializer(
        serialName = "io.github.hosseinkarami_dev.near.rpc.models.RpcStateChangesInBlockByTypeRequest",
        variants = listOf(
            Variant(serialName = "account_changes_by_block_id", kind = VariantKind.DEFAULT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.RpcStateChangesInBlockByTypeRequest.AccountChangesByBlockId }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.RpcStateChangesInBlockByTypeRequest.AccountChangesByBlockId>() as KSerializer<Any?>, fields = listOf("block_id", "account_ids", "changes_type")),
            Variant(serialName = "single_access_key_changes_by_block_id", kind = VariantKind.DEFAULT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.RpcStateChangesInBlockByTypeRequest.SingleAccessKeyChangesByBlockId }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.RpcStateChangesInBlockByTypeRequest.SingleAccessKeyChangesByBlockId>() as KSerializer<Any?>, fields = listOf("block_id", "changes_type", "keys")),
            Variant(serialName = "all_access_key_changes_by_block_id", kind = VariantKind.DEFAULT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.RpcStateChangesInBlockByTypeRequest.AllAccessKeyChangesByBlockId }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.RpcStateChangesInBlockByTypeRequest.AllAccessKeyChangesByBlockId>() as KSerializer<Any?>, fields = listOf("block_id", "account_ids", "changes_type")),
            Variant(serialName = "contract_code_changes_by_block_id", kind = VariantKind.DEFAULT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.RpcStateChangesInBlockByTypeRequest.ContractCodeChangesByBlockId }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.RpcStateChangesInBlockByTypeRequest.ContractCodeChangesByBlockId>() as KSerializer<Any?>, fields = listOf("block_id", "account_ids", "changes_type")),
            Variant(serialName = "data_changes_by_block_id", kind = VariantKind.DEFAULT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.RpcStateChangesInBlockByTypeRequest.DataChangesByBlockId }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.RpcStateChangesInBlockByTypeRequest.DataChangesByBlockId>() as KSerializer<Any?>, fields = listOf("block_id", "account_ids", "changes_type", "key_prefix_base64")),
            Variant(serialName = "account_changes_by_finality", kind = VariantKind.DEFAULT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.RpcStateChangesInBlockByTypeRequest.AccountChangesByFinality }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.RpcStateChangesInBlockByTypeRequest.AccountChangesByFinality>() as KSerializer<Any?>, fields = listOf("finality", "account_ids", "changes_type")),
            Variant(serialName = "single_access_key_changes_by_finality", kind = VariantKind.DEFAULT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.RpcStateChangesInBlockByTypeRequest.SingleAccessKeyChangesByFinality }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.RpcStateChangesInBlockByTypeRequest.SingleAccessKeyChangesByFinality>() as KSerializer<Any?>, fields = listOf("finality", "changes_type", "keys")),
            Variant(serialName = "all_access_key_changes_by_finality", kind = VariantKind.DEFAULT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.RpcStateChangesInBlockByTypeRequest.AllAccessKeyChangesByFinality }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.RpcStateChangesInBlockByTypeRequest.AllAccessKeyChangesByFinality>() as KSerializer<Any?>, fields = listOf("finality", "account_ids", "changes_type")),
            Variant(serialName = "contract_code_changes_by_finality", kind = VariantKind.DEFAULT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.RpcStateChangesInBlockByTypeRequest.ContractCodeChangesByFinality }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.RpcStateChangesInBlockByTypeRequest.ContractCodeChangesByFinality>() as KSerializer<Any?>, fields = listOf("finality", "account_ids", "changes_type")),
            Variant(serialName = "data_changes_by_finality", kind = VariantKind.DEFAULT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.RpcStateChangesInBlockByTypeRequest.DataChangesByFinality }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.RpcStateChangesInBlockByTypeRequest.DataChangesByFinality>() as KSerializer<Any?>, fields = listOf("finality", "account_ids", "changes_type", "key_prefix_base64")),
            Variant(serialName = "account_changes_by_sync_checkpoint", kind = VariantKind.DEFAULT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.RpcStateChangesInBlockByTypeRequest.AccountChangesBySyncCheckpoint }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.RpcStateChangesInBlockByTypeRequest.AccountChangesBySyncCheckpoint>() as KSerializer<Any?>, fields = listOf("sync_checkpoint", "account_ids", "changes_type")),
            Variant(serialName = "single_access_key_changes_by_sync_checkpoint", kind = VariantKind.DEFAULT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.RpcStateChangesInBlockByTypeRequest.SingleAccessKeyChangesBySyncCheckpoint }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.RpcStateChangesInBlockByTypeRequest.SingleAccessKeyChangesBySyncCheckpoint>() as KSerializer<Any?>, fields = listOf("sync_checkpoint", "changes_type", "keys")),
            Variant(serialName = "all_access_key_changes_by_sync_checkpoint", kind = VariantKind.DEFAULT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.RpcStateChangesInBlockByTypeRequest.AllAccessKeyChangesBySyncCheckpoint }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.RpcStateChangesInBlockByTypeRequest.AllAccessKeyChangesBySyncCheckpoint>() as KSerializer<Any?>, fields = listOf("sync_checkpoint", "account_ids", "changes_type")),
            Variant(serialName = "contract_code_changes_by_sync_checkpoint", kind = VariantKind.DEFAULT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.RpcStateChangesInBlockByTypeRequest.ContractCodeChangesBySyncCheckpoint }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.RpcStateChangesInBlockByTypeRequest.ContractCodeChangesBySyncCheckpoint>() as KSerializer<Any?>, fields = listOf("sync_checkpoint", "account_ids", "changes_type")),
            Variant(serialName = "data_changes_by_sync_checkpoint", kind = VariantKind.DEFAULT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.RpcStateChangesInBlockByTypeRequest.DataChangesBySyncCheckpoint }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.RpcStateChangesInBlockByTypeRequest.DataChangesBySyncCheckpoint>() as KSerializer<Any?>, fields = listOf("sync_checkpoint", "account_ids", "changes_type", "key_prefix_base64"))
        )
    )

    override val descriptor = union.descriptor
    override fun serialize(encoder: Encoder, value: RpcStateChangesInBlockByTypeRequest) = union.serialize(encoder, value)
    override fun deserialize(decoder: Decoder): RpcStateChangesInBlockByTypeRequest = union.deserialize(decoder)
}
