package io.github.hosseinkarami_dev.near.rpc.serializers

import io.github.hosseinkarami_dev.near.rpc.serializers.BlindUnionSerializer
import io.github.hosseinkarami_dev.near.rpc.serializers.Variant
import io.github.hosseinkarami_dev.near.rpc.serializers.VariantKind
import kotlinx.serialization.KSerializer
import kotlinx.serialization.builtins.ListSerializer
import kotlinx.serialization.builtins.MapSerializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import kotlinx.serialization.serializer
import io.github.hosseinkarami_dev.near.rpc.models.ActionView

object ActionViewSerializer : KSerializer<ActionView> {
    private val union: BlindUnionSerializer<ActionView> = BlindUnionSerializer(
        serialName = "io.github.hosseinkarami_dev.near.rpc.models.ActionView",
        variants = listOf(
            Variant(serialName = "CreateAccount", kind = VariantKind.OBJECT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionView.CreateAccount }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionView.CreateAccount>() as KSerializer<Any?>, objectInstance = io.github.hosseinkarami_dev.near.rpc.models.ActionView.CreateAccount),
            Variant(serialName = "DeployContract", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionView.DeployContract }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionView.DeployContract>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionView.DeployContract.DeployContractPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ActionView.DeployContract).deployContract }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ActionView.DeployContract(it as io.github.hosseinkarami_dev.near.rpc.models.ActionView.DeployContract.DeployContractPayload) }, fields = listOf("DeployContract")),
            Variant(serialName = "FunctionCall", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionView.FunctionCall }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionView.FunctionCall>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionView.FunctionCall.FunctionCallPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ActionView.FunctionCall).functionCall }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ActionView.FunctionCall(it as io.github.hosseinkarami_dev.near.rpc.models.ActionView.FunctionCall.FunctionCallPayload) }, fields = listOf("FunctionCall")),
            Variant(serialName = "Transfer", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionView.Transfer }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionView.Transfer>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionView.Transfer.TransferPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ActionView.Transfer).transfer }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ActionView.Transfer(it as io.github.hosseinkarami_dev.near.rpc.models.ActionView.Transfer.TransferPayload) }, fields = listOf("Transfer")),
            Variant(serialName = "Stake", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionView.Stake }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionView.Stake>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionView.Stake.StakePayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ActionView.Stake).stake }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ActionView.Stake(it as io.github.hosseinkarami_dev.near.rpc.models.ActionView.Stake.StakePayload) }, fields = listOf("Stake")),
            Variant(serialName = "AddKey", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionView.AddKey }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionView.AddKey>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionView.AddKey.AddKeyPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ActionView.AddKey).addKey }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ActionView.AddKey(it as io.github.hosseinkarami_dev.near.rpc.models.ActionView.AddKey.AddKeyPayload) }, fields = listOf("AddKey")),
            Variant(serialName = "DeleteKey", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionView.DeleteKey }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionView.DeleteKey>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionView.DeleteKey.DeleteKeyPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ActionView.DeleteKey).deleteKey }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ActionView.DeleteKey(it as io.github.hosseinkarami_dev.near.rpc.models.ActionView.DeleteKey.DeleteKeyPayload) }, fields = listOf("DeleteKey")),
            Variant(serialName = "DeleteAccount", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionView.DeleteAccount }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionView.DeleteAccount>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionView.DeleteAccount.DeleteAccountPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ActionView.DeleteAccount).deleteAccount }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ActionView.DeleteAccount(it as io.github.hosseinkarami_dev.near.rpc.models.ActionView.DeleteAccount.DeleteAccountPayload) }, fields = listOf("DeleteAccount")),
            Variant(serialName = "Delegate", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionView.Delegate }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionView.Delegate>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionView.Delegate.DelegatePayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ActionView.Delegate).delegate }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ActionView.Delegate(it as io.github.hosseinkarami_dev.near.rpc.models.ActionView.Delegate.DelegatePayload) }, fields = listOf("Delegate")),
            Variant(serialName = "DeployGlobalContract", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionView.DeployGlobalContract }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionView.DeployGlobalContract>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionView.DeployGlobalContract.DeployGlobalContractPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ActionView.DeployGlobalContract).deployGlobalContract }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ActionView.DeployGlobalContract(it as io.github.hosseinkarami_dev.near.rpc.models.ActionView.DeployGlobalContract.DeployGlobalContractPayload) }, fields = listOf("DeployGlobalContract")),
            Variant(serialName = "DeployGlobalContractByAccountId", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionView.DeployGlobalContractByAccountId }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionView.DeployGlobalContractByAccountId>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionView.DeployGlobalContractByAccountId.DeployGlobalContractByAccountIdPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ActionView.DeployGlobalContractByAccountId).deployGlobalContractByAccountId }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ActionView.DeployGlobalContractByAccountId(it as io.github.hosseinkarami_dev.near.rpc.models.ActionView.DeployGlobalContractByAccountId.DeployGlobalContractByAccountIdPayload) }, fields = listOf("DeployGlobalContractByAccountId")),
            Variant(serialName = "UseGlobalContract", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionView.UseGlobalContract }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionView.UseGlobalContract>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionView.UseGlobalContract.UseGlobalContractPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ActionView.UseGlobalContract).useGlobalContract }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ActionView.UseGlobalContract(it as io.github.hosseinkarami_dev.near.rpc.models.ActionView.UseGlobalContract.UseGlobalContractPayload) }, fields = listOf("UseGlobalContract")),
            Variant(serialName = "UseGlobalContractByAccountId", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionView.UseGlobalContractByAccountId }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionView.UseGlobalContractByAccountId>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionView.UseGlobalContractByAccountId.UseGlobalContractByAccountIdPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ActionView.UseGlobalContractByAccountId).useGlobalContractByAccountId }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ActionView.UseGlobalContractByAccountId(it as io.github.hosseinkarami_dev.near.rpc.models.ActionView.UseGlobalContractByAccountId.UseGlobalContractByAccountIdPayload) }, fields = listOf("UseGlobalContractByAccountId")),
            Variant(serialName = "DeterministicStateInit", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionView.DeterministicStateInit }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionView.DeterministicStateInit>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionView.DeterministicStateInit.DeterministicStateInitPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ActionView.DeterministicStateInit).deterministicStateInit }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ActionView.DeterministicStateInit(it as io.github.hosseinkarami_dev.near.rpc.models.ActionView.DeterministicStateInit.DeterministicStateInitPayload) }, fields = listOf("DeterministicStateInit")),
            Variant(serialName = "TransferToGasKey", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionView.TransferToGasKey }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionView.TransferToGasKey>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionView.TransferToGasKey.TransferToGasKeyPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ActionView.TransferToGasKey).transferToGasKey }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ActionView.TransferToGasKey(it as io.github.hosseinkarami_dev.near.rpc.models.ActionView.TransferToGasKey.TransferToGasKeyPayload) }, fields = listOf("TransferToGasKey")),
            Variant(serialName = "WithdrawFromGasKey", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionView.WithdrawFromGasKey }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionView.WithdrawFromGasKey>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionView.WithdrawFromGasKey.WithdrawFromGasKeyPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ActionView.WithdrawFromGasKey).withdrawFromGasKey }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ActionView.WithdrawFromGasKey(it as io.github.hosseinkarami_dev.near.rpc.models.ActionView.WithdrawFromGasKey.WithdrawFromGasKeyPayload) }, fields = listOf("WithdrawFromGasKey"))
        )
    )

    override val descriptor = union.descriptor
    override fun serialize(encoder: Encoder, value: ActionView) = union.serialize(encoder, value)
    override fun deserialize(decoder: Decoder): ActionView = union.deserialize(decoder)
}
