package io.github.hosseinkarami_dev.near.rpc.serializers

import io.github.hosseinkarami_dev.near.rpc.serializers.BlindUnionSerializer
import io.github.hosseinkarami_dev.near.rpc.serializers.Variant
import io.github.hosseinkarami_dev.near.rpc.serializers.VariantKind
import kotlinx.serialization.KSerializer
import kotlinx.serialization.builtins.ListSerializer
import kotlinx.serialization.builtins.MapSerializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import kotlinx.serialization.serializer
import io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind

object ActionErrorKindSerializer : KSerializer<ActionErrorKind> {
    private val union: BlindUnionSerializer<ActionErrorKind> = BlindUnionSerializer(
        serialName = "io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind",
        variants = listOf(
            Variant(serialName = "AccountAlreadyExists", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.AccountAlreadyExists }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.AccountAlreadyExists>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.AccountAlreadyExists.AccountAlreadyExistsPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.AccountAlreadyExists).accountAlreadyExists }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.AccountAlreadyExists(it as io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.AccountAlreadyExists.AccountAlreadyExistsPayload) }, fields = listOf("AccountAlreadyExists")),
            Variant(serialName = "AccountDoesNotExist", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.AccountDoesNotExist }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.AccountDoesNotExist>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.AccountDoesNotExist.AccountDoesNotExistPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.AccountDoesNotExist).accountDoesNotExist }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.AccountDoesNotExist(it as io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.AccountDoesNotExist.AccountDoesNotExistPayload) }, fields = listOf("AccountDoesNotExist")),
            Variant(serialName = "CreateAccountOnlyByRegistrar", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.CreateAccountOnlyByRegistrar }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.CreateAccountOnlyByRegistrar>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.CreateAccountOnlyByRegistrar.CreateAccountOnlyByRegistrarPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.CreateAccountOnlyByRegistrar).createAccountOnlyByRegistrar }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.CreateAccountOnlyByRegistrar(it as io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.CreateAccountOnlyByRegistrar.CreateAccountOnlyByRegistrarPayload) }, fields = listOf("CreateAccountOnlyByRegistrar")),
            Variant(serialName = "CreateAccountNotAllowed", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.CreateAccountNotAllowed }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.CreateAccountNotAllowed>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.CreateAccountNotAllowed.CreateAccountNotAllowedPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.CreateAccountNotAllowed).createAccountNotAllowed }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.CreateAccountNotAllowed(it as io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.CreateAccountNotAllowed.CreateAccountNotAllowedPayload) }, fields = listOf("CreateAccountNotAllowed")),
            Variant(serialName = "ActorNoPermission", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.ActorNoPermission }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.ActorNoPermission>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.ActorNoPermission.ActorNoPermissionPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.ActorNoPermission).actorNoPermission }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.ActorNoPermission(it as io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.ActorNoPermission.ActorNoPermissionPayload) }, fields = listOf("ActorNoPermission")),
            Variant(serialName = "DeleteKeyDoesNotExist", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.DeleteKeyDoesNotExist }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.DeleteKeyDoesNotExist>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.DeleteKeyDoesNotExist.DeleteKeyDoesNotExistPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.DeleteKeyDoesNotExist).deleteKeyDoesNotExist }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.DeleteKeyDoesNotExist(it as io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.DeleteKeyDoesNotExist.DeleteKeyDoesNotExistPayload) }, fields = listOf("DeleteKeyDoesNotExist")),
            Variant(serialName = "AddKeyAlreadyExists", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.AddKeyAlreadyExists }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.AddKeyAlreadyExists>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.AddKeyAlreadyExists.AddKeyAlreadyExistsPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.AddKeyAlreadyExists).addKeyAlreadyExists }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.AddKeyAlreadyExists(it as io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.AddKeyAlreadyExists.AddKeyAlreadyExistsPayload) }, fields = listOf("AddKeyAlreadyExists")),
            Variant(serialName = "DeleteAccountStaking", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.DeleteAccountStaking }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.DeleteAccountStaking>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.DeleteAccountStaking.DeleteAccountStakingPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.DeleteAccountStaking).deleteAccountStaking }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.DeleteAccountStaking(it as io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.DeleteAccountStaking.DeleteAccountStakingPayload) }, fields = listOf("DeleteAccountStaking")),
            Variant(serialName = "LackBalanceForState", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.LackBalanceForState }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.LackBalanceForState>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.LackBalanceForState.LackBalanceForStatePayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.LackBalanceForState).lackBalanceForState }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.LackBalanceForState(it as io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.LackBalanceForState.LackBalanceForStatePayload) }, fields = listOf("LackBalanceForState")),
            Variant(serialName = "TriesToUnstake", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.TriesToUnstake }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.TriesToUnstake>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.TriesToUnstake.TriesToUnstakePayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.TriesToUnstake).triesToUnstake }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.TriesToUnstake(it as io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.TriesToUnstake.TriesToUnstakePayload) }, fields = listOf("TriesToUnstake")),
            Variant(serialName = "TriesToStake", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.TriesToStake }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.TriesToStake>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.TriesToStake.TriesToStakePayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.TriesToStake).triesToStake }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.TriesToStake(it as io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.TriesToStake.TriesToStakePayload) }, fields = listOf("TriesToStake")),
            Variant(serialName = "InsufficientStake", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.InsufficientStake }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.InsufficientStake>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.InsufficientStake.InsufficientStakePayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.InsufficientStake).insufficientStake }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.InsufficientStake(it as io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.InsufficientStake.InsufficientStakePayload) }, fields = listOf("InsufficientStake")),
            Variant(serialName = "FunctionCallError", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.FunctionCallError }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.FunctionCallError>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.FunctionCallError>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.FunctionCallError).functionCallError }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.FunctionCallError(it as io.github.hosseinkarami_dev.near.rpc.models.FunctionCallError) }, fields = listOf("FunctionCallError")),
            Variant(serialName = "NewReceiptValidationError", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.NewReceiptValidationError }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.NewReceiptValidationError>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ReceiptValidationError>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.NewReceiptValidationError).newReceiptValidationError }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.NewReceiptValidationError(it as io.github.hosseinkarami_dev.near.rpc.models.ReceiptValidationError) }, fields = listOf("NewReceiptValidationError")),
            Variant(serialName = "OnlyImplicitAccountCreationAllowed", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.OnlyImplicitAccountCreationAllowed }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.OnlyImplicitAccountCreationAllowed>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.OnlyImplicitAccountCreationAllowed.OnlyImplicitAccountCreationAllowedPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.OnlyImplicitAccountCreationAllowed).onlyImplicitAccountCreationAllowed }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.OnlyImplicitAccountCreationAllowed(it as io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.OnlyImplicitAccountCreationAllowed.OnlyImplicitAccountCreationAllowedPayload) }, fields = listOf("OnlyImplicitAccountCreationAllowed")),
            Variant(serialName = "DeleteAccountWithLargeState", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.DeleteAccountWithLargeState }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.DeleteAccountWithLargeState>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.DeleteAccountWithLargeState.DeleteAccountWithLargeStatePayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.DeleteAccountWithLargeState).deleteAccountWithLargeState }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.DeleteAccountWithLargeState(it as io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.DeleteAccountWithLargeState.DeleteAccountWithLargeStatePayload) }, fields = listOf("DeleteAccountWithLargeState")),
            Variant(serialName = "DelegateActionInvalidSignature", kind = VariantKind.OBJECT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.DelegateActionInvalidSignature }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.DelegateActionInvalidSignature>() as KSerializer<Any?>, objectInstance = io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.DelegateActionInvalidSignature),
            Variant(serialName = "DelegateActionSenderDoesNotMatchTxReceiver", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.DelegateActionSenderDoesNotMatchTxReceiver }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.DelegateActionSenderDoesNotMatchTxReceiver>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.DelegateActionSenderDoesNotMatchTxReceiver.DelegateActionSenderDoesNotMatchTxReceiverPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.DelegateActionSenderDoesNotMatchTxReceiver).delegateActionSenderDoesNotMatchTxReceiver }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.DelegateActionSenderDoesNotMatchTxReceiver(it as io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.DelegateActionSenderDoesNotMatchTxReceiver.DelegateActionSenderDoesNotMatchTxReceiverPayload) }, fields = listOf("DelegateActionSenderDoesNotMatchTxReceiver")),
            Variant(serialName = "DelegateActionExpired", kind = VariantKind.OBJECT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.DelegateActionExpired }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.DelegateActionExpired>() as KSerializer<Any?>, objectInstance = io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.DelegateActionExpired),
            Variant(serialName = "DelegateActionAccessKeyError", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.DelegateActionAccessKeyError }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.DelegateActionAccessKeyError>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.InvalidAccessKeyError>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.DelegateActionAccessKeyError).delegateActionAccessKeyError }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.DelegateActionAccessKeyError(it as io.github.hosseinkarami_dev.near.rpc.models.InvalidAccessKeyError) }, fields = listOf("DelegateActionAccessKeyError")),
            Variant(serialName = "DelegateActionInvalidNonce", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.DelegateActionInvalidNonce }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.DelegateActionInvalidNonce>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.DelegateActionInvalidNonce.DelegateActionInvalidNoncePayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.DelegateActionInvalidNonce).delegateActionInvalidNonce }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.DelegateActionInvalidNonce(it as io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.DelegateActionInvalidNonce.DelegateActionInvalidNoncePayload) }, fields = listOf("DelegateActionInvalidNonce")),
            Variant(serialName = "DelegateActionNonceTooLarge", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.DelegateActionNonceTooLarge }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.DelegateActionNonceTooLarge>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.DelegateActionNonceTooLarge.DelegateActionNonceTooLargePayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.DelegateActionNonceTooLarge).delegateActionNonceTooLarge }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.DelegateActionNonceTooLarge(it as io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.DelegateActionNonceTooLarge.DelegateActionNonceTooLargePayload) }, fields = listOf("DelegateActionNonceTooLarge")),
            Variant(serialName = "GlobalContractDoesNotExist", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.GlobalContractDoesNotExist }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.GlobalContractDoesNotExist>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.GlobalContractDoesNotExist.GlobalContractDoesNotExistPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.GlobalContractDoesNotExist).globalContractDoesNotExist }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.GlobalContractDoesNotExist(it as io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.GlobalContractDoesNotExist.GlobalContractDoesNotExistPayload) }, fields = listOf("GlobalContractDoesNotExist")),
            Variant(serialName = "GasKeyDoesNotExist", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.GasKeyDoesNotExist }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.GasKeyDoesNotExist>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.GasKeyDoesNotExist.GasKeyDoesNotExistPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.GasKeyDoesNotExist).gasKeyDoesNotExist }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.GasKeyDoesNotExist(it as io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.GasKeyDoesNotExist.GasKeyDoesNotExistPayload) }, fields = listOf("GasKeyDoesNotExist")),
            Variant(serialName = "InsufficientGasKeyBalance", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.InsufficientGasKeyBalance }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.InsufficientGasKeyBalance>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.InsufficientGasKeyBalance.InsufficientGasKeyBalancePayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.InsufficientGasKeyBalance).insufficientGasKeyBalance }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.InsufficientGasKeyBalance(it as io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.InsufficientGasKeyBalance.InsufficientGasKeyBalancePayload) }, fields = listOf("InsufficientGasKeyBalance")),
            Variant(serialName = "GasKeyBalanceTooHigh", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.GasKeyBalanceTooHigh }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.GasKeyBalanceTooHigh>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.GasKeyBalanceTooHigh.GasKeyBalanceTooHighPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.GasKeyBalanceTooHigh).gasKeyBalanceTooHigh }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.GasKeyBalanceTooHigh(it as io.github.hosseinkarami_dev.near.rpc.models.ActionErrorKind.GasKeyBalanceTooHigh.GasKeyBalanceTooHighPayload) }, fields = listOf("GasKeyBalanceTooHigh"))
        )
    )

    override val descriptor = union.descriptor
    override fun serialize(encoder: Encoder, value: ActionErrorKind) = union.serialize(encoder, value)
    override fun deserialize(decoder: Decoder): ActionErrorKind = union.deserialize(decoder)
}
