package io.github.hosseinkarami_dev.near.rpc.serializers

import io.github.hosseinkarami_dev.near.rpc.serializers.BlindUnionSerializer
import io.github.hosseinkarami_dev.near.rpc.serializers.Variant
import io.github.hosseinkarami_dev.near.rpc.serializers.VariantKind
import kotlinx.serialization.KSerializer
import kotlinx.serialization.builtins.ListSerializer
import kotlinx.serialization.builtins.MapSerializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import kotlinx.serialization.serializer
import io.github.hosseinkarami_dev.near.rpc.models.HostError

object HostErrorSerializer : KSerializer<HostError> {
    private val union: BlindUnionSerializer<HostError> = BlindUnionSerializer(
        serialName = "io.github.hosseinkarami_dev.near.rpc.models.HostError",
        variants = listOf(
            Variant(serialName = "BadUTF16", kind = VariantKind.OBJECT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.HostError.BadUTF16 }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.HostError.BadUTF16>() as KSerializer<Any?>, objectInstance = io.github.hosseinkarami_dev.near.rpc.models.HostError.BadUTF16),
            Variant(serialName = "BadUTF8", kind = VariantKind.OBJECT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.HostError.BadUTF8 }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.HostError.BadUTF8>() as KSerializer<Any?>, objectInstance = io.github.hosseinkarami_dev.near.rpc.models.HostError.BadUTF8),
            Variant(serialName = "GasExceeded", kind = VariantKind.OBJECT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.HostError.GasExceeded }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.HostError.GasExceeded>() as KSerializer<Any?>, objectInstance = io.github.hosseinkarami_dev.near.rpc.models.HostError.GasExceeded),
            Variant(serialName = "GasLimitExceeded", kind = VariantKind.OBJECT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.HostError.GasLimitExceeded }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.HostError.GasLimitExceeded>() as KSerializer<Any?>, objectInstance = io.github.hosseinkarami_dev.near.rpc.models.HostError.GasLimitExceeded),
            Variant(serialName = "BalanceExceeded", kind = VariantKind.OBJECT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.HostError.BalanceExceeded }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.HostError.BalanceExceeded>() as KSerializer<Any?>, objectInstance = io.github.hosseinkarami_dev.near.rpc.models.HostError.BalanceExceeded),
            Variant(serialName = "EmptyMethodName", kind = VariantKind.OBJECT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.HostError.EmptyMethodName }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.HostError.EmptyMethodName>() as KSerializer<Any?>, objectInstance = io.github.hosseinkarami_dev.near.rpc.models.HostError.EmptyMethodName),
            Variant(serialName = "GuestPanic", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.HostError.GuestPanic }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.HostError.GuestPanic>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.HostError.GuestPanic.GuestPanicPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.HostError.GuestPanic).guestPanic }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.HostError.GuestPanic(it as io.github.hosseinkarami_dev.near.rpc.models.HostError.GuestPanic.GuestPanicPayload) }, fields = listOf("GuestPanic")),
            Variant(serialName = "IntegerOverflow", kind = VariantKind.OBJECT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.HostError.IntegerOverflow }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.HostError.IntegerOverflow>() as KSerializer<Any?>, objectInstance = io.github.hosseinkarami_dev.near.rpc.models.HostError.IntegerOverflow),
            Variant(serialName = "InvalidPromiseIndex", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.HostError.InvalidPromiseIndex }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.HostError.InvalidPromiseIndex>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.HostError.InvalidPromiseIndex.InvalidPromiseIndexPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.HostError.InvalidPromiseIndex).invalidPromiseIndex }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.HostError.InvalidPromiseIndex(it as io.github.hosseinkarami_dev.near.rpc.models.HostError.InvalidPromiseIndex.InvalidPromiseIndexPayload) }, fields = listOf("InvalidPromiseIndex")),
            Variant(serialName = "CannotAppendActionToJointPromise", kind = VariantKind.OBJECT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.HostError.CannotAppendActionToJointPromise }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.HostError.CannotAppendActionToJointPromise>() as KSerializer<Any?>, objectInstance = io.github.hosseinkarami_dev.near.rpc.models.HostError.CannotAppendActionToJointPromise),
            Variant(serialName = "CannotReturnJointPromise", kind = VariantKind.OBJECT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.HostError.CannotReturnJointPromise }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.HostError.CannotReturnJointPromise>() as KSerializer<Any?>, objectInstance = io.github.hosseinkarami_dev.near.rpc.models.HostError.CannotReturnJointPromise),
            Variant(serialName = "InvalidPromiseResultIndex", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.HostError.InvalidPromiseResultIndex }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.HostError.InvalidPromiseResultIndex>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.HostError.InvalidPromiseResultIndex.InvalidPromiseResultIndexPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.HostError.InvalidPromiseResultIndex).invalidPromiseResultIndex }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.HostError.InvalidPromiseResultIndex(it as io.github.hosseinkarami_dev.near.rpc.models.HostError.InvalidPromiseResultIndex.InvalidPromiseResultIndexPayload) }, fields = listOf("InvalidPromiseResultIndex")),
            Variant(serialName = "InvalidRegisterId", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.HostError.InvalidRegisterId }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.HostError.InvalidRegisterId>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.HostError.InvalidRegisterId.InvalidRegisterIdPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.HostError.InvalidRegisterId).invalidRegisterId }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.HostError.InvalidRegisterId(it as io.github.hosseinkarami_dev.near.rpc.models.HostError.InvalidRegisterId.InvalidRegisterIdPayload) }, fields = listOf("InvalidRegisterId")),
            Variant(serialName = "IteratorWasInvalidated", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.HostError.IteratorWasInvalidated }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.HostError.IteratorWasInvalidated>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.HostError.IteratorWasInvalidated.IteratorWasInvalidatedPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.HostError.IteratorWasInvalidated).iteratorWasInvalidated }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.HostError.IteratorWasInvalidated(it as io.github.hosseinkarami_dev.near.rpc.models.HostError.IteratorWasInvalidated.IteratorWasInvalidatedPayload) }, fields = listOf("IteratorWasInvalidated")),
            Variant(serialName = "MemoryAccessViolation", kind = VariantKind.OBJECT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.HostError.MemoryAccessViolation }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.HostError.MemoryAccessViolation>() as KSerializer<Any?>, objectInstance = io.github.hosseinkarami_dev.near.rpc.models.HostError.MemoryAccessViolation),
            Variant(serialName = "InvalidReceiptIndex", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.HostError.InvalidReceiptIndex }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.HostError.InvalidReceiptIndex>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.HostError.InvalidReceiptIndex.InvalidReceiptIndexPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.HostError.InvalidReceiptIndex).invalidReceiptIndex }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.HostError.InvalidReceiptIndex(it as io.github.hosseinkarami_dev.near.rpc.models.HostError.InvalidReceiptIndex.InvalidReceiptIndexPayload) }, fields = listOf("InvalidReceiptIndex")),
            Variant(serialName = "InvalidIteratorIndex", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.HostError.InvalidIteratorIndex }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.HostError.InvalidIteratorIndex>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.HostError.InvalidIteratorIndex.InvalidIteratorIndexPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.HostError.InvalidIteratorIndex).invalidIteratorIndex }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.HostError.InvalidIteratorIndex(it as io.github.hosseinkarami_dev.near.rpc.models.HostError.InvalidIteratorIndex.InvalidIteratorIndexPayload) }, fields = listOf("InvalidIteratorIndex")),
            Variant(serialName = "InvalidAccountId", kind = VariantKind.OBJECT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.HostError.InvalidAccountId }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.HostError.InvalidAccountId>() as KSerializer<Any?>, objectInstance = io.github.hosseinkarami_dev.near.rpc.models.HostError.InvalidAccountId),
            Variant(serialName = "InvalidMethodName", kind = VariantKind.OBJECT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.HostError.InvalidMethodName }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.HostError.InvalidMethodName>() as KSerializer<Any?>, objectInstance = io.github.hosseinkarami_dev.near.rpc.models.HostError.InvalidMethodName),
            Variant(serialName = "InvalidPublicKey", kind = VariantKind.OBJECT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.HostError.InvalidPublicKey }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.HostError.InvalidPublicKey>() as KSerializer<Any?>, objectInstance = io.github.hosseinkarami_dev.near.rpc.models.HostError.InvalidPublicKey),
            Variant(serialName = "ProhibitedInView", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.HostError.ProhibitedInView }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.HostError.ProhibitedInView>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.HostError.ProhibitedInView.ProhibitedInViewPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.HostError.ProhibitedInView).prohibitedInView }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.HostError.ProhibitedInView(it as io.github.hosseinkarami_dev.near.rpc.models.HostError.ProhibitedInView.ProhibitedInViewPayload) }, fields = listOf("ProhibitedInView")),
            Variant(serialName = "NumberOfLogsExceeded", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.HostError.NumberOfLogsExceeded }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.HostError.NumberOfLogsExceeded>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.HostError.NumberOfLogsExceeded.NumberOfLogsExceededPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.HostError.NumberOfLogsExceeded).numberOfLogsExceeded }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.HostError.NumberOfLogsExceeded(it as io.github.hosseinkarami_dev.near.rpc.models.HostError.NumberOfLogsExceeded.NumberOfLogsExceededPayload) }, fields = listOf("NumberOfLogsExceeded")),
            Variant(serialName = "KeyLengthExceeded", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.HostError.KeyLengthExceeded }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.HostError.KeyLengthExceeded>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.HostError.KeyLengthExceeded.KeyLengthExceededPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.HostError.KeyLengthExceeded).keyLengthExceeded }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.HostError.KeyLengthExceeded(it as io.github.hosseinkarami_dev.near.rpc.models.HostError.KeyLengthExceeded.KeyLengthExceededPayload) }, fields = listOf("KeyLengthExceeded")),
            Variant(serialName = "ValueLengthExceeded", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.HostError.ValueLengthExceeded }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.HostError.ValueLengthExceeded>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.HostError.ValueLengthExceeded.ValueLengthExceededPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.HostError.ValueLengthExceeded).valueLengthExceeded }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.HostError.ValueLengthExceeded(it as io.github.hosseinkarami_dev.near.rpc.models.HostError.ValueLengthExceeded.ValueLengthExceededPayload) }, fields = listOf("ValueLengthExceeded")),
            Variant(serialName = "TotalLogLengthExceeded", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.HostError.TotalLogLengthExceeded }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.HostError.TotalLogLengthExceeded>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.HostError.TotalLogLengthExceeded.TotalLogLengthExceededPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.HostError.TotalLogLengthExceeded).totalLogLengthExceeded }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.HostError.TotalLogLengthExceeded(it as io.github.hosseinkarami_dev.near.rpc.models.HostError.TotalLogLengthExceeded.TotalLogLengthExceededPayload) }, fields = listOf("TotalLogLengthExceeded")),
            Variant(serialName = "NumberPromisesExceeded", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.HostError.NumberPromisesExceeded }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.HostError.NumberPromisesExceeded>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.HostError.NumberPromisesExceeded.NumberPromisesExceededPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.HostError.NumberPromisesExceeded).numberPromisesExceeded }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.HostError.NumberPromisesExceeded(it as io.github.hosseinkarami_dev.near.rpc.models.HostError.NumberPromisesExceeded.NumberPromisesExceededPayload) }, fields = listOf("NumberPromisesExceeded")),
            Variant(serialName = "NumberInputDataDependenciesExceeded", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.HostError.NumberInputDataDependenciesExceeded }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.HostError.NumberInputDataDependenciesExceeded>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.HostError.NumberInputDataDependenciesExceeded.NumberInputDataDependenciesExceededPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.HostError.NumberInputDataDependenciesExceeded).numberInputDataDependenciesExceeded }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.HostError.NumberInputDataDependenciesExceeded(it as io.github.hosseinkarami_dev.near.rpc.models.HostError.NumberInputDataDependenciesExceeded.NumberInputDataDependenciesExceededPayload) }, fields = listOf("NumberInputDataDependenciesExceeded")),
            Variant(serialName = "ReturnedValueLengthExceeded", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.HostError.ReturnedValueLengthExceeded }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.HostError.ReturnedValueLengthExceeded>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.HostError.ReturnedValueLengthExceeded.ReturnedValueLengthExceededPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.HostError.ReturnedValueLengthExceeded).returnedValueLengthExceeded }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.HostError.ReturnedValueLengthExceeded(it as io.github.hosseinkarami_dev.near.rpc.models.HostError.ReturnedValueLengthExceeded.ReturnedValueLengthExceededPayload) }, fields = listOf("ReturnedValueLengthExceeded")),
            Variant(serialName = "ContractSizeExceeded", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.HostError.ContractSizeExceeded }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.HostError.ContractSizeExceeded>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.HostError.ContractSizeExceeded.ContractSizeExceededPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.HostError.ContractSizeExceeded).contractSizeExceeded }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.HostError.ContractSizeExceeded(it as io.github.hosseinkarami_dev.near.rpc.models.HostError.ContractSizeExceeded.ContractSizeExceededPayload) }, fields = listOf("ContractSizeExceeded")),
            Variant(serialName = "Deprecated", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.HostError.Deprecated }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.HostError.Deprecated>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.HostError.Deprecated.DeprecatedPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.HostError.Deprecated).deprecated }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.HostError.Deprecated(it as io.github.hosseinkarami_dev.near.rpc.models.HostError.Deprecated.DeprecatedPayload) }, fields = listOf("Deprecated")),
            Variant(serialName = "ECRecoverError", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.HostError.ECRecoverError }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.HostError.ECRecoverError>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.HostError.ECRecoverError.ECRecoverErrorPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.HostError.ECRecoverError).eCRecoverError }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.HostError.ECRecoverError(it as io.github.hosseinkarami_dev.near.rpc.models.HostError.ECRecoverError.ECRecoverErrorPayload) }, fields = listOf("ECRecoverError")),
            Variant(serialName = "AltBn128InvalidInput", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.HostError.AltBn128InvalidInput }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.HostError.AltBn128InvalidInput>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.HostError.AltBn128InvalidInput.AltBn128InvalidInputPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.HostError.AltBn128InvalidInput).altBn128InvalidInput }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.HostError.AltBn128InvalidInput(it as io.github.hosseinkarami_dev.near.rpc.models.HostError.AltBn128InvalidInput.AltBn128InvalidInputPayload) }, fields = listOf("AltBn128InvalidInput")),
            Variant(serialName = "Ed25519VerifyInvalidInput", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.HostError.Ed25519VerifyInvalidInput }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.HostError.Ed25519VerifyInvalidInput>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.HostError.Ed25519VerifyInvalidInput.Ed25519VerifyInvalidInputPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.HostError.Ed25519VerifyInvalidInput).ed25519VerifyInvalidInput }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.HostError.Ed25519VerifyInvalidInput(it as io.github.hosseinkarami_dev.near.rpc.models.HostError.Ed25519VerifyInvalidInput.Ed25519VerifyInvalidInputPayload) }, fields = listOf("Ed25519VerifyInvalidInput"))
        )
    )

    override val descriptor = union.descriptor
    override fun serialize(encoder: Encoder, value: HostError) = union.serialize(encoder, value)
    override fun deserialize(decoder: Decoder): HostError = union.deserialize(decoder)
}
