package io.github.hosseinkarami_dev.near.rpc.serializers

import io.github.hosseinkarami_dev.near.rpc.serializers.BlindUnionSerializer
import io.github.hosseinkarami_dev.near.rpc.serializers.Variant
import io.github.hosseinkarami_dev.near.rpc.serializers.VariantKind
import kotlinx.serialization.KSerializer
import kotlinx.serialization.builtins.ListSerializer
import kotlinx.serialization.builtins.MapSerializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import kotlinx.serialization.serializer
import io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError

object InvalidTxErrorSerializer : KSerializer<InvalidTxError> {
    private val union: BlindUnionSerializer<InvalidTxError> = BlindUnionSerializer(
        serialName = "io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError",
        variants = listOf(
            Variant(serialName = "InvalidAccessKeyError", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.InvalidAccessKeyError }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.InvalidAccessKeyError>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.InvalidAccessKeyError>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.InvalidAccessKeyError).invalidAccessKeyError }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.InvalidAccessKeyError(it as io.github.hosseinkarami_dev.near.rpc.models.InvalidAccessKeyError) }, fields = listOf("InvalidAccessKeyError")),
            Variant(serialName = "InvalidSignerId", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.InvalidSignerId }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.InvalidSignerId>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.InvalidSignerId.InvalidSignerIdPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.InvalidSignerId).invalidSignerId }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.InvalidSignerId(it as io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.InvalidSignerId.InvalidSignerIdPayload) }, fields = listOf("InvalidSignerId")),
            Variant(serialName = "SignerDoesNotExist", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.SignerDoesNotExist }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.SignerDoesNotExist>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.SignerDoesNotExist.SignerDoesNotExistPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.SignerDoesNotExist).signerDoesNotExist }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.SignerDoesNotExist(it as io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.SignerDoesNotExist.SignerDoesNotExistPayload) }, fields = listOf("SignerDoesNotExist")),
            Variant(serialName = "InvalidNonce", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.InvalidNonce }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.InvalidNonce>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.InvalidNonce.InvalidNoncePayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.InvalidNonce).invalidNonce }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.InvalidNonce(it as io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.InvalidNonce.InvalidNoncePayload) }, fields = listOf("InvalidNonce")),
            Variant(serialName = "NonceTooLarge", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.NonceTooLarge }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.NonceTooLarge>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.NonceTooLarge.NonceTooLargePayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.NonceTooLarge).nonceTooLarge }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.NonceTooLarge(it as io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.NonceTooLarge.NonceTooLargePayload) }, fields = listOf("NonceTooLarge")),
            Variant(serialName = "InvalidReceiverId", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.InvalidReceiverId }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.InvalidReceiverId>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.InvalidReceiverId.InvalidReceiverIdPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.InvalidReceiverId).invalidReceiverId }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.InvalidReceiverId(it as io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.InvalidReceiverId.InvalidReceiverIdPayload) }, fields = listOf("InvalidReceiverId")),
            Variant(serialName = "InvalidSignature", kind = VariantKind.OBJECT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.InvalidSignature }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.InvalidSignature>() as KSerializer<Any?>, objectInstance = io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.InvalidSignature),
            Variant(serialName = "NotEnoughBalance", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.NotEnoughBalance }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.NotEnoughBalance>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.NotEnoughBalance.NotEnoughBalancePayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.NotEnoughBalance).notEnoughBalance }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.NotEnoughBalance(it as io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.NotEnoughBalance.NotEnoughBalancePayload) }, fields = listOf("NotEnoughBalance")),
            Variant(serialName = "LackBalanceForState", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.LackBalanceForState }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.LackBalanceForState>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.LackBalanceForState.LackBalanceForStatePayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.LackBalanceForState).lackBalanceForState }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.LackBalanceForState(it as io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.LackBalanceForState.LackBalanceForStatePayload) }, fields = listOf("LackBalanceForState")),
            Variant(serialName = "CostOverflow", kind = VariantKind.OBJECT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.CostOverflow }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.CostOverflow>() as KSerializer<Any?>, objectInstance = io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.CostOverflow),
            Variant(serialName = "InvalidChain", kind = VariantKind.OBJECT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.InvalidChain }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.InvalidChain>() as KSerializer<Any?>, objectInstance = io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.InvalidChain),
            Variant(serialName = "Expired", kind = VariantKind.OBJECT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.Expired }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.Expired>() as KSerializer<Any?>, objectInstance = io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.Expired),
            Variant(serialName = "ActionsValidation", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.ActionsValidation }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.ActionsValidation>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.ActionsValidation).actionsValidation }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.ActionsValidation(it as io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError) }, fields = listOf("ActionsValidation")),
            Variant(serialName = "TransactionSizeExceeded", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.TransactionSizeExceeded }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.TransactionSizeExceeded>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.TransactionSizeExceeded.TransactionSizeExceededPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.TransactionSizeExceeded).transactionSizeExceeded }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.TransactionSizeExceeded(it as io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.TransactionSizeExceeded.TransactionSizeExceededPayload) }, fields = listOf("TransactionSizeExceeded")),
            Variant(serialName = "InvalidTransactionVersion", kind = VariantKind.OBJECT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.InvalidTransactionVersion }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.InvalidTransactionVersion>() as KSerializer<Any?>, objectInstance = io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.InvalidTransactionVersion),
            Variant(serialName = "StorageError", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.StorageError }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.StorageError>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.StorageError>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.StorageError).storageError }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.StorageError(it as io.github.hosseinkarami_dev.near.rpc.models.StorageError) }, fields = listOf("StorageError")),
            Variant(serialName = "ShardCongested", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.ShardCongested }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.ShardCongested>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.ShardCongested.ShardCongestedPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.ShardCongested).shardCongested }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.ShardCongested(it as io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.ShardCongested.ShardCongestedPayload) }, fields = listOf("ShardCongested")),
            Variant(serialName = "ShardStuck", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.ShardStuck }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.ShardStuck>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.ShardStuck.ShardStuckPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.ShardStuck).shardStuck }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.ShardStuck(it as io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.ShardStuck.ShardStuckPayload) }, fields = listOf("ShardStuck")),
            Variant(serialName = "InvalidNonceIndex", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.InvalidNonceIndex }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.InvalidNonceIndex>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.InvalidNonceIndex.InvalidNonceIndexPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.InvalidNonceIndex).invalidNonceIndex }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.InvalidNonceIndex(it as io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.InvalidNonceIndex.InvalidNonceIndexPayload) }, fields = listOf("InvalidNonceIndex")),
            Variant(serialName = "NotEnoughGasKeyBalance", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.NotEnoughGasKeyBalance }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.NotEnoughGasKeyBalance>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.NotEnoughGasKeyBalance.NotEnoughGasKeyBalancePayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.NotEnoughGasKeyBalance).notEnoughGasKeyBalance }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.NotEnoughGasKeyBalance(it as io.github.hosseinkarami_dev.near.rpc.models.InvalidTxError.NotEnoughGasKeyBalance.NotEnoughGasKeyBalancePayload) }, fields = listOf("NotEnoughGasKeyBalance"))
        )
    )

    override val descriptor = union.descriptor
    override fun serialize(encoder: Encoder, value: InvalidTxError) = union.serialize(encoder, value)
    override fun deserialize(decoder: Decoder): InvalidTxError = union.deserialize(decoder)
}
