package io.github.hosseinkarami_dev.near.rpc.serializers

import io.github.hosseinkarami_dev.near.rpc.serializers.BlindUnionSerializer
import io.github.hosseinkarami_dev.near.rpc.serializers.Variant
import io.github.hosseinkarami_dev.near.rpc.serializers.VariantKind
import kotlinx.serialization.KSerializer
import kotlinx.serialization.builtins.ListSerializer
import kotlinx.serialization.builtins.MapSerializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import kotlinx.serialization.serializer
import io.github.hosseinkarami_dev.near.rpc.models.ReceiptValidationError

object ReceiptValidationErrorSerializer : KSerializer<ReceiptValidationError> {
    private val union: BlindUnionSerializer<ReceiptValidationError> = BlindUnionSerializer(
        serialName = "io.github.hosseinkarami_dev.near.rpc.models.ReceiptValidationError",
        variants = listOf(
            Variant(serialName = "InvalidPredecessorId", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ReceiptValidationError.InvalidPredecessorId }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ReceiptValidationError.InvalidPredecessorId>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ReceiptValidationError.InvalidPredecessorId.InvalidPredecessorIdPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ReceiptValidationError.InvalidPredecessorId).invalidPredecessorId }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ReceiptValidationError.InvalidPredecessorId(it as io.github.hosseinkarami_dev.near.rpc.models.ReceiptValidationError.InvalidPredecessorId.InvalidPredecessorIdPayload) }, fields = listOf("InvalidPredecessorId")),
            Variant(serialName = "InvalidReceiverId", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ReceiptValidationError.InvalidReceiverId }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ReceiptValidationError.InvalidReceiverId>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ReceiptValidationError.InvalidReceiverId.InvalidReceiverIdPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ReceiptValidationError.InvalidReceiverId).invalidReceiverId }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ReceiptValidationError.InvalidReceiverId(it as io.github.hosseinkarami_dev.near.rpc.models.ReceiptValidationError.InvalidReceiverId.InvalidReceiverIdPayload) }, fields = listOf("InvalidReceiverId")),
            Variant(serialName = "InvalidSignerId", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ReceiptValidationError.InvalidSignerId }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ReceiptValidationError.InvalidSignerId>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ReceiptValidationError.InvalidSignerId.InvalidSignerIdPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ReceiptValidationError.InvalidSignerId).invalidSignerId }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ReceiptValidationError.InvalidSignerId(it as io.github.hosseinkarami_dev.near.rpc.models.ReceiptValidationError.InvalidSignerId.InvalidSignerIdPayload) }, fields = listOf("InvalidSignerId")),
            Variant(serialName = "InvalidDataReceiverId", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ReceiptValidationError.InvalidDataReceiverId }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ReceiptValidationError.InvalidDataReceiverId>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ReceiptValidationError.InvalidDataReceiverId.InvalidDataReceiverIdPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ReceiptValidationError.InvalidDataReceiverId).invalidDataReceiverId }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ReceiptValidationError.InvalidDataReceiverId(it as io.github.hosseinkarami_dev.near.rpc.models.ReceiptValidationError.InvalidDataReceiverId.InvalidDataReceiverIdPayload) }, fields = listOf("InvalidDataReceiverId")),
            Variant(serialName = "ReturnedValueLengthExceeded", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ReceiptValidationError.ReturnedValueLengthExceeded }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ReceiptValidationError.ReturnedValueLengthExceeded>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ReceiptValidationError.ReturnedValueLengthExceeded.ReturnedValueLengthExceededPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ReceiptValidationError.ReturnedValueLengthExceeded).returnedValueLengthExceeded }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ReceiptValidationError.ReturnedValueLengthExceeded(it as io.github.hosseinkarami_dev.near.rpc.models.ReceiptValidationError.ReturnedValueLengthExceeded.ReturnedValueLengthExceededPayload) }, fields = listOf("ReturnedValueLengthExceeded")),
            Variant(serialName = "NumberInputDataDependenciesExceeded", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ReceiptValidationError.NumberInputDataDependenciesExceeded }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ReceiptValidationError.NumberInputDataDependenciesExceeded>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ReceiptValidationError.NumberInputDataDependenciesExceeded.NumberInputDataDependenciesExceededPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ReceiptValidationError.NumberInputDataDependenciesExceeded).numberInputDataDependenciesExceeded }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ReceiptValidationError.NumberInputDataDependenciesExceeded(it as io.github.hosseinkarami_dev.near.rpc.models.ReceiptValidationError.NumberInputDataDependenciesExceeded.NumberInputDataDependenciesExceededPayload) }, fields = listOf("NumberInputDataDependenciesExceeded")),
            Variant(serialName = "ActionsValidation", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ReceiptValidationError.ActionsValidation }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ReceiptValidationError.ActionsValidation>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ReceiptValidationError.ActionsValidation).actionsValidation }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ReceiptValidationError.ActionsValidation(it as io.github.hosseinkarami_dev.near.rpc.models.ActionsValidationError) }, fields = listOf("ActionsValidation")),
            Variant(serialName = "ReceiptSizeExceeded", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ReceiptValidationError.ReceiptSizeExceeded }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ReceiptValidationError.ReceiptSizeExceeded>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ReceiptValidationError.ReceiptSizeExceeded.ReceiptSizeExceededPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ReceiptValidationError.ReceiptSizeExceeded).receiptSizeExceeded }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ReceiptValidationError.ReceiptSizeExceeded(it as io.github.hosseinkarami_dev.near.rpc.models.ReceiptValidationError.ReceiptSizeExceeded.ReceiptSizeExceededPayload) }, fields = listOf("ReceiptSizeExceeded")),
            Variant(serialName = "InvalidRefundTo", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ReceiptValidationError.InvalidRefundTo }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ReceiptValidationError.InvalidRefundTo>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ReceiptValidationError.InvalidRefundTo.InvalidRefundToPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ReceiptValidationError.InvalidRefundTo).invalidRefundTo }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ReceiptValidationError.InvalidRefundTo(it as io.github.hosseinkarami_dev.near.rpc.models.ReceiptValidationError.InvalidRefundTo.InvalidRefundToPayload) }, fields = listOf("InvalidRefundTo"))
        )
    )

    override val descriptor = union.descriptor
    override fun serialize(encoder: Encoder, value: ReceiptValidationError) = union.serialize(encoder, value)
    override fun deserialize(decoder: Decoder): ReceiptValidationError = union.deserialize(decoder)
}
