package io.github.hosseinkarami_dev.near.rpc.serializers

import io.github.hosseinkarami_dev.near.rpc.serializers.BlindUnionSerializer
import io.github.hosseinkarami_dev.near.rpc.serializers.Variant
import io.github.hosseinkarami_dev.near.rpc.serializers.VariantKind
import kotlinx.serialization.KSerializer
import kotlinx.serialization.builtins.ListSerializer
import kotlinx.serialization.builtins.MapSerializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import kotlinx.serialization.serializer
import io.github.hosseinkarami_dev.near.rpc.models.ValidatorKickoutReason

object ValidatorKickoutReasonSerializer : KSerializer<ValidatorKickoutReason> {
    private val union: BlindUnionSerializer<ValidatorKickoutReason> = BlindUnionSerializer(
        serialName = "io.github.hosseinkarami_dev.near.rpc.models.ValidatorKickoutReason",
        variants = listOf(
            Variant(serialName = "_UnusedSlashed", kind = VariantKind.OBJECT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ValidatorKickoutReason.UnusedSlashed }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ValidatorKickoutReason.UnusedSlashed>() as KSerializer<Any?>, objectInstance = io.github.hosseinkarami_dev.near.rpc.models.ValidatorKickoutReason.UnusedSlashed),
            Variant(serialName = "NotEnoughBlocks", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ValidatorKickoutReason.NotEnoughBlocks }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ValidatorKickoutReason.NotEnoughBlocks>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ValidatorKickoutReason.NotEnoughBlocks.NotEnoughBlocksPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ValidatorKickoutReason.NotEnoughBlocks).notEnoughBlocks }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ValidatorKickoutReason.NotEnoughBlocks(it as io.github.hosseinkarami_dev.near.rpc.models.ValidatorKickoutReason.NotEnoughBlocks.NotEnoughBlocksPayload) }, fields = listOf("NotEnoughBlocks")),
            Variant(serialName = "NotEnoughChunks", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ValidatorKickoutReason.NotEnoughChunks }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ValidatorKickoutReason.NotEnoughChunks>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ValidatorKickoutReason.NotEnoughChunks.NotEnoughChunksPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ValidatorKickoutReason.NotEnoughChunks).notEnoughChunks }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ValidatorKickoutReason.NotEnoughChunks(it as io.github.hosseinkarami_dev.near.rpc.models.ValidatorKickoutReason.NotEnoughChunks.NotEnoughChunksPayload) }, fields = listOf("NotEnoughChunks")),
            Variant(serialName = "Unstaked", kind = VariantKind.OBJECT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ValidatorKickoutReason.Unstaked }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ValidatorKickoutReason.Unstaked>() as KSerializer<Any?>, objectInstance = io.github.hosseinkarami_dev.near.rpc.models.ValidatorKickoutReason.Unstaked),
            Variant(serialName = "NotEnoughStake", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ValidatorKickoutReason.NotEnoughStake }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ValidatorKickoutReason.NotEnoughStake>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ValidatorKickoutReason.NotEnoughStake.NotEnoughStakePayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ValidatorKickoutReason.NotEnoughStake).notEnoughStake }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ValidatorKickoutReason.NotEnoughStake(it as io.github.hosseinkarami_dev.near.rpc.models.ValidatorKickoutReason.NotEnoughStake.NotEnoughStakePayload) }, fields = listOf("NotEnoughStake")),
            Variant(serialName = "DidNotGetASeat", kind = VariantKind.OBJECT, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ValidatorKickoutReason.DidNotGetASeat }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ValidatorKickoutReason.DidNotGetASeat>() as KSerializer<Any?>, objectInstance = io.github.hosseinkarami_dev.near.rpc.models.ValidatorKickoutReason.DidNotGetASeat),
            Variant(serialName = "NotEnoughChunkEndorsements", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ValidatorKickoutReason.NotEnoughChunkEndorsements }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ValidatorKickoutReason.NotEnoughChunkEndorsements>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ValidatorKickoutReason.NotEnoughChunkEndorsements.NotEnoughChunkEndorsementsPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ValidatorKickoutReason.NotEnoughChunkEndorsements).notEnoughChunkEndorsements }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ValidatorKickoutReason.NotEnoughChunkEndorsements(it as io.github.hosseinkarami_dev.near.rpc.models.ValidatorKickoutReason.NotEnoughChunkEndorsements.NotEnoughChunkEndorsementsPayload) }, fields = listOf("NotEnoughChunkEndorsements")),
            Variant(serialName = "ProtocolVersionTooOld", kind = VariantKind.WRAPPED, isInstance = { it is io.github.hosseinkarami_dev.near.rpc.models.ValidatorKickoutReason.ProtocolVersionTooOld }, fullSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ValidatorKickoutReason.ProtocolVersionTooOld>() as KSerializer<Any?>, valueSerializer = serializer<io.github.hosseinkarami_dev.near.rpc.models.ValidatorKickoutReason.ProtocolVersionTooOld.ProtocolVersionTooOldPayload>() as KSerializer<Any?>, valueGetter = { (it as io.github.hosseinkarami_dev.near.rpc.models.ValidatorKickoutReason.ProtocolVersionTooOld).protocolVersionTooOld }, valueBuilder = { io.github.hosseinkarami_dev.near.rpc.models.ValidatorKickoutReason.ProtocolVersionTooOld(it as io.github.hosseinkarami_dev.near.rpc.models.ValidatorKickoutReason.ProtocolVersionTooOld.ProtocolVersionTooOldPayload) }, fields = listOf("ProtocolVersionTooOld"))
        )
    )

    override val descriptor = union.descriptor
    override fun serialize(encoder: Encoder, value: ValidatorKickoutReason) = union.serialize(encoder, value)
    override fun deserialize(decoder: Decoder): ValidatorKickoutReason = union.deserialize(decoder)
}
