package io.github.hosseinkarami_dev.near.rpc.presentation.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme Colors
val LightPrimary = Color(0xFF006C7A)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFF9CF1FF)
val LightOnPrimaryContainer = Color(0xFF002025)
val LightSecondary = Color(0xFF4B6268)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFCEE7EE)
val LightOnSecondaryContainer = Color(0xFF061F24)
val LightTertiary = Color(0xFF555E7D)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFDCE1FF)
val LightOnTertiaryContainer = Color(0xFF111B37)
val LightError = Color(0xFFBA1A1A)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnError = Color(0xFFFFFFFF)
val LightOnErrorContainer = Color(0xFF410002)
val LightBackground = Color(0xFFFBFCFD)
val LightOnBackground = Color(0xFF191C1D)
val LightSurface = Color(0xFFFBFCFD)
val LightOnSurface = Color(0xFF191C1D)
val LightSurfaceVariant = Color(0xFFDBE4E6)
val LightOnSurfaceVariant = Color(0xFF3F484A)
val LightOutline = Color(0xFF6F797B)

// Dark Theme Colors
val DarkPrimary = Color(0xFF81D4E3)
val DarkOnPrimary = Color(0xFF00373E)
val DarkPrimaryContainer = Color(0xFF004F59)
val DarkOnPrimaryContainer = Color(0xFF9CF1FF)
val DarkSecondary = Color(0xFFB2CBD2)
val DarkOnSecondary = Color(0xFF1C343A)
val DarkSecondaryContainer = Color(0xFF334A50)
val DarkOnSecondaryContainer = Color(0xFFCEE7EE)
val DarkTertiary = Color(0xFFBCC5EA)
val DarkOnTertiary = Color(0xFF27304D)
val DarkTertiaryContainer = Color(0xFF3E4665)
val DarkOnTertiaryContainer = Color(0xFFDCE1FF)
val DarkError = Color(0xFFFFB4AB)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnError = Color(0xFF690005)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF191C1D)
val DarkOnBackground = Color(0xFFE1E3E4)
val DarkSurface = Color(0xFF191C1D)
val DarkOnSurface = Color(0xFFE1E3E4)
val DarkSurfaceVariant = Color(0xFF3F484A)
val DarkOnSurfaceVariant = Color(0xFFBFC8CA)
val DarkOutline = Color(0xFF899295)
